# Generated by Django 3.1.3 on 2021-03-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_activity',
            old_name='n_column',
            new_name='n_columns',
        ),
    ]
